version: "3.3"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: cloud
      MYSQL_PASSWORD: mysql
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  app_backend:
    build:
      context: ./cloud_backend_app
      dockerfile: Dockerfile
    ports:
      - 8070:8070
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cloud?allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - db
  app_frontend:
    build:
      context: ./netology-diplom-frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080